services:
    db:
        container_name: db
        build:
            context: ./DB
        image: db
        networks:
            - todo-network
        restart: no
        volumes:
            - ./data.json:./data.json
networks:
    todo-network:
        name: todo-network
